apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapa-povesti-z-cech
  labels:
    app: mapa-povesti-z-cech

spec:
  selector:
    matchLabels:
      app: mapa-povesti-z-cech
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100
  template:
    metadata:
      labels:
        app: mapa-povesti-z-cech
    spec:
      containers:
        - name: mapa-povesti-z-cech
          image: docker.io/cajovahouba/mapa-povesti-z-cech:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000