name: Build and push image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        TAG=$(cat .image_tag)
        docker build . --file Dockerfile --tag "docker.io/cajovahouba/mapa-povesti-z-cech:$TAG"
        docker push docker.io/cajovahouba/mapa-povesti-z-cech:$TAG
